---
kind: Service
apiVersion: v1
metadata:
  name: dataverse
  labels:
    app.kubernetes.io/name: dataverse
    app.kubernetes.io/version: "5.3"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
    - port: 8009
      name: ajp
      targetPort: 8009
      protocol: TCP
  selector:
    app.kubernetes.io/name: dataverse
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/component: appserver
